# import * from "./../../../../backend/public-api/v1/schema.gql"


mutation updateTask($req: UpdateTaskRequest!) {
    updateTask(req: $req) {
        task {
            id
        }
    }
}

query getTaskForEdit($req: GetTaskRequest!) {
    getTask(req: $req) {
        task {
            taskType
            title
            maxMark
            courseId
            body
            attachedFileUrl
        }
    }
}
query getTaskWithResult($req: GetTaskRequest!) {
    getTask(req: $req) {
        task {
            taskType
            title
            maxMark
            courseId
            body
            attachedFileUrl
            author {
                id
                login
            }
            myTaskResult {
                id
                lastUpdate
                body
                fileUrl
                check {
                    comment
                    score
                    lastUpdate
                    author {
                        id
                        login
                        avaUrl
                    }
                }
            }
        }
    }
}

mutation createGroup($req: CreateGroupRequest!) {
    createGroup(req: $req) {
        group {
            id
        }
    }
}

mutation deleteGroup($req: DeleteGroupRequest!) {
    deleteGroup(req: $req) {
        group {
            id
        }
    }
}

mutation updateGroup($req: UpdateGroupRequest!) {
    updateGroup(req: $req) {
        group {
            id
        }
    }
}

query getFullGroup(
    $groupReq: GetGroupRequest!, 
    $membersReq: GetGroupMembersRequest!,
    $coursesReq: GetGroupCoursesRequest!
) {
    getGroup(req: $groupReq) {
        group {
            name
            creationDate
            getMembers(req: $membersReq) {
                total
                data {
                    id
                    login
                    fullname
                    role
                    avaUrl
                }
            }
            getCourses(req: $coursesReq) {
                total
                data {
                    id
                    name   
                }
            }
        }
    }
 }


query getGroupCourses(
    $groupReq: GetGroupRequest!, 
    $coursesReq: GetGroupCoursesRequest!
) {
    getGroup(req: $groupReq) {
        group {
            getCourses(req: $coursesReq) {
                total
                data {
                    id
                    name   
                }
            }
        }
    }
}

query getGroupMembers(
    $groupReq: GetGroupRequest!, 
    $membersReq: GetGroupMembersRequest!
) {
    getGroup(req: $groupReq) {
        group {
            getMembers(req: $membersReq) {
                total
                data {
                    id
                    login
                    fullname
                    role
                    avaUrl
                }
            }
        }
    }
}

query getGroup($req: GetGroupRequest!) {
    getGroup(req: $req) {
        group {
            name
            creationDate
        }
    }
}

query getGroups($req: GetGroupsRequest!) {
    getGroups(req: $req) {
        total
        data {
            id
            name
            getMembers(req: { limit: 0, page: 1 }) {
                total
            }
        }
    }
}


query getCourse($courseReq: GetCourseRequest!, $tasksReq: GetCourseTasksRequest!) {
    getCourse(req: $courseReq) {
        course {
            description
            name
            publicationDate
            getTasks(req: $tasksReq) {
                total
                data {
                    id
                    taskType
                    title
                    maxMark
                }
            }
        }
    }
}

query getCourses($req: GetCoursesRequest!) {
    getCourses(req: $req) {
        total
        data {
            id
            name
            description
        }
    }
}

query getUsers($req: GetUsersRequest!) {
    getUsers(req: $req) {
        total
        data {
            id
            role
            login
            fullname
            avaUrl
            group {
                id
                name
            }
        }
    }
}

query getUserForEdit($req: GetUserRequest!) {
    getUser(req: $req) {
        user {
            id
            login
            role
            fullname
            registeredAt
            avaUrl
            isDisabled
            groupId
        }
    }
}

query getUser($req: GetUserRequest!) {
    getUser(req: $req) {
        user {
            id
            login
            role
            fullname
            registeredAt
            avaUrl
            isDisabled
            group {
                id
                name
            }
        }
    }
}

mutation updateUser($req: UpdateUserRequest!) {
    updateUser(req: $req) {
        user {
            isDisabled
        }
    }
}

mutation updateMe($req: UpdateMeRequest!) {
    updateMe(req: $req) {
        me {
            isDisabled
        }
    }
}