# import * from "./../../../../backend/public-api/v1/schema.gql"

mutation createGroup($req: CreateGroupRequest!) {
    createGroup(req: $req) {
        group {
            id
        }
    }
}

mutation deleteGroup($req: DeleteGroupRequest!) {
    deleteGroup(req: $req) {
        group {
            id
        }
    }
}

mutation updateGroup($req: UpdateGroupRequest!) {
    updateGroup(req: $req) {
        group {
            id
        }
    }
}

query getGroup($groupReq: GetGroupRequest!, $membersReq: GetGroupMembersRequest!) {
    getGroup(req: $groupReq) {
        group {
            name
            creationDate
            getMembers(req: $membersReq) {
                total
                data {
                    id
                    login
                    fullname
                    role
                    avaUrl
                }
            }
        }
    }
}

query getGroups($req: GetGroupsRequest!) {
    getGroups(req: $req) {
        total
        data {
            id
            name
            getMembers(req: { limit: 0, page: 1 }) {
                total
            }
        }
    }
}


query getCourse($courseReq: GetCourseRequest!, $tasksReq: GetCourseTasksRequest!) {
    getCourse(req: $courseReq) {
        course {
            description
            name
            publicationDate
            getTasks(req: $tasksReq) {
                total
                data {
                    id
                    taskType
                    title
                    maxMark
                }
            }
        }
    }
}

query getCourses($req: GetCoursesRequest!) {
    getCourses(req: $req) {
        total
        data {
            id
            name
            description
        }
    }
}

query getUsers($req: GetUsersRequest!) {
    getUsers(req: $req) {
        total
        data {
            id
            role
            login
            fullname
            avaUrl
        }
    }
}

query getUser($req: GetUserRequest!) {
    getUser(req: $req) {
        user {
            id
            login
            role
            fullname
            registeredAt
            avaUrl
            isDisabled
        }
    }
}

mutation updateUser($req: UpdateUserRequest!) {
    updateUser(req: $req) {
        user {
            isDisabled
        }
    }
}

mutation updateMe($req: UpdateMeRequest!) {
    updateMe(req: $req) {
        me {
            isDisabled
        }
    }
}